import assert from"node:assert/strict";import test from"node:test";
import{calculate}from"../../../public/assets/js/modules/calculadora-financiamento.js";import{validCoordinates}from"../../../public/assets/js/modules/mapa.js";import{validImages}from"../../../public/assets/js/modules/galeria.js";import{addComparison}from"../../../public/assets/js/modules/comparador.js";import{findSimilar}from"../../../public/assets/js/modules/imoveis-similares.js";import{normalizeAmenities}from"../../../public/assets/js/modules/comodidades.js";import{youtubeId}from"../../../public/assets/js/modules/video.js";import{safeTour}from"../../../public/assets/js/modules/tour-360.js";import{contactLinks}from"../../../public/assets/js/modules/contato.js";import{updateRecent}from"../../../public/assets/js/modules/vistos-recentemente.js";
test("coordenadas e URLs condicionais",()=>{assert.equal(validCoordinates({latitude:-23,longitude:-51}),true);assert.equal(validCoordinates({latitude:91,longitude:0}),false);assert.equal(validImages([{url:"javascript:alert(1)"}]).length,0)});
test("SAC e Price",()=>{const sac=calculate({price:100000,down:20000,annualRate:12,months:120,system:"sac"}),price=calculate({price:100000,down:20000,annualRate:12,months:120,system:"price"});assert.ok(sac.first>sac.last);assert.equal(price.first,price.last);assert.ok(sac.total>80000&&price.total>80000);assert.throws(()=>calculate({price:-1}))});
test("canais codificam dados automáticos",()=>{const links=contactLinks({whatsapp:"+55 43 99999-9999",telephone:"(43)3333-4444",email:"a@example.com"},"Portal Londrinense A&B");assert.match(links.whatsapp,/Portal%20Londrinense%20A%26B/);assert.equal(links.telephone,"tel:4333334444");assert.match(links.email,/mailto:a@example.com/)});
test("comparador limita quatro e recentes removem duplicados",()=>{assert.deepEqual(addComparison(["1","2","3","4"],"5"),["1","2","3","4"]);assert.deepEqual(updateRecent([{slug:"a",at:1},{slug:"b",at:2}],"a").map(x=>x.slug),["a","b"])});
test("similares são determinísticos",()=>{const base={id:"x",cidade:"L",tipo:"casa",finalidade:"venda",preco:100},cards=[{...base,id:"b",preco:105},{...base,id:"a",preco:105},{...base,id:"x"}];assert.deepEqual(findSimilar(base,cards).map(x=>x.id),["a","b"])});
test("comodidades preservam texto como texto e removem duplicatas",()=>assert.deepEqual(normalizeAmenities([" <img onerror=alert(1)>"," <img onerror=alert(1)> "]),["<img onerror=alert(1)>"]));
test("YouTube e tour rejeitam entradas perigosas",()=>{assert.equal(youtubeId("https://www.youtube.com/watch?v=abcdefghijk"),"abcdefghijk");assert.equal(youtubeId("https://evil.example/watch?v=abcdefghijk"),"");assert.equal(safeTour("javascript:alert(1)"),null);assert.equal(safeTour("https://bit.ly/x"),null);assert.equal(safeTour("https://tour.example/path").hostname,"tour.example")});
