const api=globalThis.ADMIN_API||"https://api-imoveis.londrinense.net";
const login=document.querySelector("#login form"),acoes=document.querySelector("#acoes"),estado=document.querySelector("#estado");
async function send(path,method="POST",body){const response=await fetch(`${api}${path}`,{method,credentials:"include",headers:body?{"content-type":"application/json"}:{},body:body?JSON.stringify(body):undefined});if(!response.ok)throw new Error();return response.json();}
login.addEventListener("submit",async event=>{event.preventDefault();try{const result=await send("/api/login","POST",Object.fromEntries(new FormData(login)));estado.textContent="Acesso autorizado";login.parentElement.hidden=true;acoes.hidden=false;if(result.papel!=="superadmin"){document.querySelector("#sync").hidden=true;document.querySelector("#cliente").hidden=true;document.querySelector('[name="cliente_id"]').value=login.usuario.value;}}catch{estado.textContent="Credenciais inválidas ou acesso temporariamente limitado";}});
document.querySelector("#sync").onclick=async()=>{try{await send("/api/sincronizar");estado.textContent="Solicitação registrada";}catch{estado.textContent="Operação não autorizada";}};
document.querySelector("#cliente").addEventListener("submit",async event=>{event.preventDefault();try{await send("/api/clientes","PUT",Object.fromEntries(new FormData(event.currentTarget)));estado.textContent="Cliente salvo";}catch{estado.textContent="Não foi possível salvar o cliente";}});
document.querySelector("#feed").addEventListener("submit",async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget)),id=data.cliente_id;delete data.cliente_id;try{await send(`/api/clientes/${encodeURIComponent(id)}/feed`,"PUT",data);estado.textContent="Feed salvo";}catch{estado.textContent="Não foi possível salvar o feed";}});
document.querySelector("#sync-cliente").onclick=async()=>{const id=document.querySelector('[name="cliente_id"]').value;try{await send(`/api/clientes/${encodeURIComponent(id)}/sincronizar`);estado.textContent="Sincronização individual registrada";}catch{estado.textContent="Operação não autorizada";}};
document.querySelector("#sair").onclick=async()=>{try{await send("/api/logout");}finally{location.reload();}};
