import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const load=(files,extra={})=>{const storage=new Map(),context={console,Intl,URL,URLSearchParams,setTimeout,clearTimeout,location:{origin:'https://blog.example',pathname:'/p/imoveis.html',search:'?tipo=casa&pagina=2',hash:''},document:{getElementById:()=>null},localStorage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)},...extra};context.window=context;context.globalThis=context;vm.createContext(context);for(const file of files)vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});return{context,storage}};
const core=['public/blogger/core/common.js','public/blogger/core/favoritos.js','public/blogger/core/utils.js'];

test('parâmetros, URL, BRL e escaping são seguros',()=>{const {context}=load(core),C=context.Londrinense.Common;assert.deepEqual({...C.params()}, {tipo:'casa',pagina:'2'});assert.equal(C.url('/p/imovel.html',{id:'abc'}),'/p/imovel.html?id=abc');assert.match(C.brl(420000),/420\.000/);assert.equal(C.escapeHtml('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;')});
test('filtros, ordenação e janela de paginação',()=>{const {context}=load(core),U=context.Londrinense.Utils,items=[{tipo:'casa',preco:20,quartos:3,area:100},{tipo:'apartamento',preco:10,quartos:2,area:60}];assert.equal(U.filtrar(items,{tipo:'casa',quartos:'2',area_min:'90'}).length,1);assert.equal(U.ordenar(items,'preco_asc')[0].preco,10);assert.deepEqual([...U.paginas(50,100)], [1,'…',48,49,50,51,52,'…',100])});
test('favoritos persistem e comparação limita quatro IDs',()=>{const {context}=load(core),L=context.Londrinense;L.Favoritos.adicionar('imovel-1');assert.equal(L.Favoritos.contem('imovel-1'),true);L.Favoritos.alternar('imovel-1');assert.deepEqual([...L.Favoritos.listar()],[]);for(let i=1;i<=5;i++)L.Utils.toggleComparison('id-'+i);assert.deepEqual([...L.Utils.comparisons()],['id-1','id-2','id-3','id-4'])});
test('coordenadas só aceitam latitude e longitude válidas',()=>{const {context}=load(core),coords=context.Londrinense.Utils.coords;assert.deepEqual([...coords({location:{latitude:'-23.3',longitude:'-51.16'}})],[-23.3,-51.16]);assert.equal(coords({location:{latitude:100,longitude:0}}),null);assert.equal(coords({}),null)});
test('dados lê manifesto, índice todos e cacheia requests',async()=>{let calls=0;const manifest={todos:{partes:['indices/todos/parte-0001.json'],total:1}},fetch=async url=>{calls++;return {ok:true,json:async()=>String(url).endsWith('manifesto.json')?manifest:[{id:'abc'}]}};const {context}=load(['public/blogger/core/common.js','public/blogger/core/dados.js'],{fetch});const one=await context.Londrinense.Dados.getTodos(),two=await context.Londrinense.Dados.getTodos();assert.equal(one[0].id,'abc');assert.equal(two[0].id,'abc');assert.equal(calls,2)});
test('renderizador de card neutraliza HTML dos read models',()=>{const {context}=load(core),html=context.Londrinense.Utils.card({id:'abc',titulo:'<img src=x onerror=alert(1)>',tipo:'casa',finalidade:'venda',preco:1});assert.doesNotMatch(html,/<img src=x onerror/);assert.match(html,/&lt;img src=x onerror=alert\(1\)&gt;/)});
