import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const load=(files,extra={})=>{const storage=new Map(),context={console,Intl,URL,URLSearchParams,setTimeout,clearTimeout,location:{origin:'https://blog.example',pathname:'/p/imoveis.html',search:'?tipo=casa&pagina=2',hash:''},document:{getElementById:()=>null},localStorage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)},...extra};context.window=context;context.globalThis=context;vm.createContext(context);for(const file of files)vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});return{context,storage}};
const core=['public/blogger/core/common.js','public/blogger/core/favoritos.js','public/blogger/core/utils.js'];

test('parâmetros, URL, BRL e escaping são seguros',()=>{const {context}=load(core),C=context.Londrinense.Common;assert.deepEqual({...C.params()}, {tipo:'casa',pagina:'2'});assert.equal(C.url('/p/imovel.html',{id:'abc'}),'/p/imovel.html?id=abc');assert.match(C.brl(420000),/420\.000/);assert.equal(C.escapeHtml('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;')});
test('filtros, ordenação e janela de paginação',()=>{const {context}=load(core),U=context.Londrinense.Utils,items=[{tipo:'casa',preco:20,quartos:3,area:100},{tipo:'apartamento',preco:10,quartos:2,area:60}];assert.equal(U.filtrar(items,{tipo:'casa',quartos:'2',area_min:'90'}).length,1);assert.equal(U.ordenar(items,'preco_asc')[0].preco,10);assert.deepEqual([...U.paginas(50,100)], [1,'…',48,49,50,51,52,'…',100])});
test('favoritos persistem e comparação limita quatro IDs',()=>{const {context}=load(core),L=context.Londrinense;L.Favoritos.adicionar('imovel-1');assert.equal(L.Favoritos.contem('imovel-1'),true);L.Favoritos.alternar('imovel-1');assert.deepEqual([...L.Favoritos.listar()],[]);for(let i=1;i<=5;i++)L.Utils.toggleComparison('id-'+i);assert.deepEqual([...L.Utils.comparisons()],['id-1','id-2','id-3','id-4'])});
test('coordenadas só aceitam latitude e longitude válidas',()=>{const {context}=load(core),coords=context.Londrinense.Utils.coords;assert.deepEqual([...coords({location:{latitude:'-23.3',longitude:'-51.16'}})],[-23.3,-51.16]);assert.equal(coords({location:{latitude:100,longitude:0}}),null);assert.equal(coords({}),null)});
test('dados lê manifesto, índice todos e cacheia requests',async()=>{let calls=0;const manifest={todos:{partes:['indices/todos/parte-0001.json'],total:1}},fetch=async url=>{calls++;return {ok:true,json:async()=>String(url).endsWith('manifesto.json')?manifest:[{id:'abc'}]}};const {context}=load(['public/blogger/core/common.js','public/blogger/core/dados.js'],{fetch});const one=await context.Londrinense.Dados.getTodos(),two=await context.Londrinense.Dados.getTodos();assert.equal(one[0].id,'abc');assert.equal(two[0].id,'abc');assert.equal(calls,2)});
test('renderizador de card neutraliza HTML dos read models',()=>{const {context}=load(core),html=context.Londrinense.Utils.card({id:'abc',titulo:'<img src=x onerror=alert(1)>',tipo:'casa',finalidade:'venda',preco:1});assert.doesNotMatch(html,/<img src=x onerror/);assert.match(html,/&lt;img src=x onerror=alert\(1\)&gt;/)});

test('card compacto preserva dados e usa ícones Remix consistentes',()=>{const {context}=load(core),item={id:'abc',titulo:'Casa central',tipo:'casa',finalidade:'venda',preco:420000,bairro:'Centro',cidade:'Londrina',quartos:3,banheiros:2,vagas:1,area:120},html=context.Londrinense.Utils.card(item),css=fs.readFileSync('public/blogger/template1/portal.css','utf8');for(const text of ['Casa central','R$','Centro, Londrina','3','2','1','120','Ver imóvel'])assert.ok(html.includes(text));for(const icon of ['ri-heart-line','ri-map-pin-line','ri-hotel-bed-line','ri-showers-line','ri-car-line','ri-ruler-line','ri-scales-3-line','ri-share-line'])assert.match(html,new RegExp(icon));assert.match(css,/\.ln-card__media\{[^}]*aspect-ratio:16\/9/);assert.match(css,/\.ln-card__body\{padding:15px/);assert.match(css,/\.ln-card__body h3\{[^}]*font-size:1\.03rem/)});

const mapHarness=({boundsValid=true}={})=>{const calls={maps:0,removed:0,invalidated:0,fit:0,setView:0,details:0},classNames=new Set(),map={invalidateSize(){calls.invalidated++},fitBounds(){calls.fit++},setView(){calls.setView++},remove(){calls.removed++}},Leaflet={map(){calls.maps++;return map},tileLayer(){return{addTo(){}}},marker(){return{addTo(){return this},bindPopup(){return this}}},latLngBounds(){return{isValid:()=>boundsValid}}},root={_html:'',firstElementChild:null,classList:{add:value=>classNames.add(value),remove:value=>classNames.delete(value)}};Object.defineProperty(root,'innerHTML',{get(){return this._html},set(value){this._html=value;this.firstElementChild=value.includes('class="ln-map"')?{}:null}});const context={console,Intl,URL,URLSearchParams,setTimeout,clearTimeout,requestAnimationFrame:callback=>callback(),document:{createElement:()=>({}),head:{appendChild(){}}},L:Leaflet,Londrinense:{Common:{escapeHtml:value=>String(value??''),brl:value=>String(value),url:path=>path},Utils:{coords:item=>item.location?[item.location.latitude,item.location.longitude]:null,media:()=>''},Dados:{getImovel:async item=>{calls.details++;return item}},Config:{mapConcurrency:4,urls:{imovel:'/imovel'}}}};context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync('public/blogger/template1/mapa.js','utf8'),context);return{calls,context,root,classNames}};

test('mapa invalida tamanho, enquadra bounds válidos e não duplica instâncias',async()=>{const {calls,context,root}=mapHarness(),items=[{id:'1',titulo:'A',location:{latitude:-23.3,longitude:-51.1}},{id:'2',titulo:'B',location:{latitude:-23.4,longitude:-51.2}}];await context.Londrinense.Mapa.render(root,items);assert.equal(calls.maps,1);assert.ok(calls.invalidated>=1);assert.equal(calls.fit,1);assert.equal(calls.setView,0);await context.Londrinense.Mapa.render(root,items);assert.equal(calls.maps,2);assert.equal(calls.removed,1);context.Londrinense.Mapa.destroy(root);assert.equal(calls.removed,2)});

test('mapa usa zoom adequado para um ponto e respeita bounds inválidos',async()=>{const one=mapHarness(),item={id:'1',titulo:'A',location:{latitude:-23.3,longitude:-51.1}};await one.context.Londrinense.Mapa.render(one.root,[item]);assert.equal(one.calls.setView,1);assert.equal(one.calls.fit,0);const invalid=mapHarness({boundsValid:false});await invalid.context.Londrinense.Mapa.render(invalid.root,[item,{...item,id:'2'}]);assert.equal(invalid.calls.fit,0)});

test('mapa trata ausência de coordenadas sem criar Leaflet e mantém busca concorrente',async()=>{const {calls,context,root}=mapHarness();await context.Londrinense.Mapa.render(root,[{id:'1'},{id:'2'}]);assert.equal(calls.details,2);assert.equal(calls.maps,0);assert.match(root.innerHTML,/Não há imóveis com localização disponível/)});
