import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {webcrypto} from 'node:crypto';
if(!globalThis.crypto)globalThis.crypto=webcrypto;if(!globalThis.btoa)globalThis.btoa=value=>Buffer.from(value,'binary').toString('base64');if(!globalThis.atob)globalThis.atob=value=>Buffer.from(value,'base64').toString('binary');
const {testables}=await import('../../src/admin/worker.js');
const origin='https://imoveis.londrinense.net',sensitiveMarker=['test','credential','value'].join('-'),env={SESSION_SECRET:'s'.repeat(48),ADMIN_ORIGIN:origin,GITHUB_OWNER:'owner',GITHUB_REPO:'repo',GITHUB_BRANCH:'main',GITHUB_ADMIN_TOKEN:sensitiveMarker};
const request=cookie=>new Request('https://api.example/api/diagnostico/github',{headers:{origin,cookie}});
const cookie=async role=>`session=${await testables.session({sub:'subject',email:`${role.toLowerCase()}@example.com`,role,nome:role},env.SESSION_SECRET)}`;
const githubMock=(failure,clientsMissing=false)=>globalThis.fetch=async(raw,options={})=>{const url=String(raw);if(failure){const response=failure(url,options);if(response)return response}if(url.includes('/contents/private/clientes?')&&clientsMissing)return Response.json({message:'not found'},{status:404});return Response.json(url.includes('/contents/')?{type:'file',content:'e30=',sha:'sha'}:{name:'ok'})};

test('diagnóstico permite MASTER e SUPERADMIN e bloqueia ADMIN e CLIENTE',async()=>{githubMock();for(const role of ['MASTER','SUPERADMIN'])assert.equal((await testables.handle(request(await cookie(role)),env)).status,200);for(const role of ['ADMIN','CLIENTE'])assert.equal((await testables.handle(request(await cookie(role)),env)).status,403)});
test('Fine-grained PAT usa endpoint do repositório, headers REST oficiais e somente GET',async()=>{const calls=[];globalThis.fetch=async(raw,options={})=>{calls.push({url:String(raw),options});return Response.json({name:'ok'})};const body=await (await testables.handle(request(await cookie('MASTER')),env)).json();assert.equal(body.ok,true);assert.match(calls[0].url,/api\.github\.com\/repos\/owner\/repo$/);assert.equal(calls[0].options.headers.authorization,`Bearer ${sensitiveMarker}`);assert.equal(calls[0].options.headers.accept,'application/vnd.github+json');assert.equal(calls[0].options.headers['x-github-api-version'],'2022-11-28');assert.equal(calls[0].options.headers['user-agent'],'portal-londrinense-admin');assert.ok(calls.every(call=>(call.options.method||'GET')==='GET'));assert.ok(calls.some(call=>call.url.includes('/branches/main')));assert.ok(calls.some(call=>call.url.includes('/contents/ARQUITETURA.md?ref=main')))});
test('diagnóstico completo é somente leitura e relata recurso de clientes ausente como erro',async()=>{const methods=[];globalThis.fetch=async(raw,options={})=>{methods.push(options.method||'GET');return String(raw).includes('/contents/private/clientes?')?Response.json({message:'not found'},{status:404}):Response.json({name:'ok'})};const response=await testables.handle(request(await cookie('MASTER')),env),body=await response.json();assert.equal(body.ok,false);assert.equal(body.github.clientes,'erro');assert.equal(body.codigo,'ARQUIVO_NAO_ENCONTRADO');assert.deepEqual(new Set(methods),new Set(['GET']))});
for(const [label,status,code,match,failedStep] of [['token rejeitado',401,'AUTENTICACAO','/repos/owner/repo','autenticacao'],['sem permissão',403,'PERMISSAO','/repos/owner/repo','autenticacao'],['repositório ausente',404,'REPOSITORIO','/repos/owner/repo','repositorio'],['branch ausente',404,'BRANCH','/branches/','branch'],['Contents ausente',404,'ARQUIVO_NAO_ENCONTRADO','/contents/ARQUITETURA.md','leitura'],['GitHub indisponível',500,'GITHUB_INDISPONIVEL','/repos/owner/repo','repositorio']])test(`${label} produz ${code} sem expor segredo`,async()=>{githubMock(url=>url.includes(match)?Response.json({message:'raw'},{status}):null);const response=await testables.handle(request(await cookie('MASTER')),env),text=await response.text(),body=JSON.parse(text);assert.equal(body.ok,false);assert.equal(body.codigo,code);assert.equal(body.github[failedStep],'erro');assert.equal(text.includes(sensitiveMarker),false);assert.doesNotMatch(text,/authorization/i)});
test('módulos administrativos carregam com GitHub disponível e preservam indisponibilidade real',async()=>{const signed=await cookie('MASTER'),headers={origin,cookie:signed};githubMock();for(const path of ['/api/administradores','/api/clientes','/api/dashboard']){const response=await testables.handle(new Request(`https://api.example${path}`,{headers}),env);assert.equal(response.status,200,path)}globalThis.fetch=async()=>Response.json({message:'unavailable'},{status:503});const response=await testables.handle(new Request('https://api.example/api/dashboard',{headers}),env),body=await response.json();assert.equal(response.status,503);assert.equal(body.codigo,'GITHUB_INDISPONIVEL');assert.doesNotMatch(JSON.stringify(body),new RegExp(sensitiveMarker))});
test('token ausente falha na configuração sem chamar GitHub',async()=>{let called=false;globalThis.fetch=async()=>{called=true;throw new Error('unexpected')};const body=await (await testables.handle(request(await cookie('MASTER')),{...env,GITHUB_ADMIN_TOKEN:String()})).json();assert.equal(body.codigo,'CONFIGURACAO');assert.equal(body.github.configuracao,'erro');assert.equal(called,false)});
test('erro inesperado de transporte produz GITHUB_INESPERADO',async()=>{globalThis.fetch=async()=>{throw new Error('network details')};const body=await (await testables.handle(request(await cookie('MASTER')),env)).json();assert.equal(body.ok,false);assert.equal(body.codigo,'GITHUB_INESPERADO')});
test('artefato contém rota, menu e apresentação segura do diagnóstico',()=>{const html=fs.readFileSync('public/painel/index.html','utf8'),router=fs.readFileSync('public/painel/modulos/router.js','utf8'),screen=fs.readFileSync('public/painel/modulos/diagnostico.js','utf8');assert.match(html,/href="#\/diagnostico"[^>]+title="Diagnóstico"/);assert.match(router,/parts\[0\]==="diagnostico"/);for(const text of ['Diagnóstico do sistema','Executar diagnóstico','NÃO VERIFICADO','Nenhuma escrita foi executada.'])assert.match(screen,new RegExp(text));for(const secret of ['GITHUB_ADMIN_TOKEN','SESSION_SECRET','CLOUDFLARE_API_TOKEN','authorization'])assert.doesNotMatch(screen,new RegExp(secret,'i'))});
