import test from 'node:test';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
if(!globalThis.crypto)globalThis.crypto=webcrypto;if(!globalThis.btoa)globalThis.btoa=value=>Buffer.from(value,'binary').toString('base64');if(!globalThis.atob)globalThis.atob=value=>Buffer.from(value,'base64').toString('binary');
const {testables}=await import('../../src/admin/worker.js');
const origin='https://imoveis.londrinense.net',sensitiveMarker=['test','credential','value'].join('-'),env={SESSION_SECRET:'s'.repeat(48),ADMIN_ORIGIN:origin,GITHUB_OWNER:'owner',GITHUB_REPO:'repo',GITHUB_BRANCH:'main',GITHUB_ADMIN_TOKEN:sensitiveMarker};
const request=cookie=>new Request('https://api.example/api/diagnostico/github',{headers:{origin,cookie}});
const cookie=async role=>`session=${await testables.session({sub:'subject',email:`${role.toLowerCase()}@example.com`,role,nome:role},env.SESSION_SECRET)}`;
const githubMock=(failure,clientsMissing=false)=>globalThis.fetch=async raw=>{const url=String(raw);if(failure){const response=failure(url);if(response)return response}if(url.includes('/contents/private/clientes?')&&clientsMissing)return Response.json({message:'not found'},{status:404});return Response.json(url.includes('/contents/')?{type:'file',content:'e30=',sha:'sha'}:{name:'ok'})};

test('diagnóstico permite MASTER e SUPERADMIN e bloqueia ADMIN e CLIENTE',async()=>{githubMock();for(const role of ['MASTER','SUPERADMIN'])assert.equal((await testables.handle(request(await cookie(role)),env)).status,200);for(const role of ['ADMIN','CLIENTE'])assert.equal((await testables.handle(request(await cookie(role)),env)).status,403)});
test('diagnóstico GitHub OK é somente leitura e clientes ausentes não falham integração',async()=>{const methods=[];globalThis.fetch=async(raw,options={})=>{methods.push(options.method||'GET');return String(raw).includes('/contents/private/clientes?')?Response.json({message:'not found'},{status:404}):Response.json({name:'ok'})};const response=await testables.handle(request(await cookie('MASTER')),env),body=await response.json();assert.equal(body.ok,true);assert.equal(body.github.clientes,'ausente');assert.deepEqual(new Set(methods),new Set(['GET']))});
for(const [label,status,code,match] of [['token rejeitado',401,'AUTENTICACAO','/repos/owner/repo'],['sem permissão',403,'PERMISSAO','/repos/owner/repo'],['branch ausente',404,'BRANCH','/branches/'],['GitHub indisponível',500,'GITHUB_INDISPONIVEL','/repos/owner/repo']])test(`${label} produz ${code} sem expor segredo`,async()=>{githubMock(url=>url.includes(match)?Response.json({message:'raw'},{status}):null);const response=await testables.handle(request(await cookie('MASTER')),env),text=await response.text(),body=JSON.parse(text);assert.equal(body.ok,false);assert.equal(body.codigo,code);assert.equal(text.includes(sensitiveMarker),false);assert.doesNotMatch(text,/authorization/i)});
test('erro inesperado de transporte produz GITHUB_INESPERADO',async()=>{globalThis.fetch=async()=>{throw new Error('network details')};const body=await (await testables.handle(request(await cookie('MASTER')),env)).json();assert.equal(body.ok,false);assert.equal(body.codigo,'GITHUB_INESPERADO')});
