import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
if(!globalThis.crypto)globalThis.crypto=(await import('node:crypto')).webcrypto;if(!globalThis.btoa)globalThis.btoa=v=>Buffer.from(v,'binary').toString('base64');if(!globalThis.atob)globalThis.atob=v=>Buffer.from(v,'base64').toString('binary');
const {testables}=await import('../../src/admin/worker.js');
const origin='https://imoveis.londrinense.net';
async function env(){return{SESSION_SECRET:'s'.repeat(48),ADMIN_ORIGIN:origin,GITHUB_OWNER:'o',GITHUB_REPO:'r',GITHUB_BRANCH:'main',GITHUB_ADMIN_TOKEN:'x',BOOTSTRAP_MASTER_PASSWORD_HASH:await testables.encodedPasswordHash('bootstrap-master'),BOOTSTRAP_ADMIN_PASSWORD_HASH:await testables.encodedPasswordHash('bootstrap-admin')}}
const request=(path,method='GET',body,headers={})=>new Request(`https://api.example${path}`,{method,headers:{origin,...headers,...(body?{'content-type':'application/json'}:{})},body:body&&JSON.stringify(body)});
test('cookie de sessão é restrito',()=>{const c=testables.cookie('x');for(const x of ['HttpOnly','Secure','SameSite=Strict'])assert.match(c,new RegExp(x))});
test('sessão MASTER assinada autentica e adulteração falha',async()=>{const e=await env(),token=await testables.session('master','MASTER',e.SESSION_SECRET);assert.equal((await testables.authenticate(new Request('https://x',{headers:{cookie:`session=${token}`}}),e)).sub,'master');assert.equal(await testables.authenticate(new Request('https://x',{headers:{cookie:`session=${token}x`}}),e),null)});
test('não autenticado não acessa API administrativa',async()=>assert.equal((await testables.handle(request('/api/administradores'),await env())).status,401));
test('bootstrap exige troca antes do painel',async()=>{globalThis.fetch=async()=>new Response('{}',{status:404});const e=await env(),r=await testables.handle(request('/api/login','POST',{usuario:'master',senha:'bootstrap-master'}),e);assert.equal(r.status,200);assert.equal((await r.json()).troca_senha_obrigatoria,true);const token=r.headers.get('set-cookie').match(/session=([^;]+)/)[1];const blocked=await testables.handle(request('/api/dashboard','GET',null,{cookie:`session=${token}`}),e);assert.equal(blocked.status,403)});
test('senha usa hash forte e nunca texto puro',async()=>{const hash=await testables.encodedPasswordHash('definitiva-segura');assert.match(hash,/^pbkdf2-sha256\$310000\$/);assert.ok(!hash.includes('definitiva-segura'));assert.equal(await testables.verifyPassword('definitiva-segura',hash),true);assert.equal(await testables.verifyPassword('antiga',hash),false)});
test('proteções MASTER e autorização estão no Worker',()=>{const s=fs.readFileSync('src/admin/worker.js','utf8');assert.match(s,/id==="master".*action==="disable".*request\.method==="DELETE"/s);assert.match(s,/MASTER não pode perder o perfil/);assert.match(s,/if\(!requireMaster\(auth\)\)return json\(\{erro:"Proibido"\},403\)/);assert.doesNotMatch(s,/write-file|path\s*[:=]\s*data\./)});
test('ADMIN não recebe sessão MASTER',async()=>{const e=await env(),token=await testables.session('admin','ADMIN',e.SESSION_SECRET);const auth=await testables.authenticate(new Request('https://x',{headers:{cookie:`session=${token}`}}),e);assert.equal(auth.role,'ADMIN')});
test('painel implementa troca obrigatória e gestão operacional',()=>{const html=fs.readFileSync('public/painel/index.html','utf8'),js=fs.readFileSync('public/painel/painel.js','utf8');assert.match(html,/id="troca-senha"/);assert.match(html,/Administradores/);assert.match(html,/Sincronizações/);assert.match(js,/troca_senha_obrigatoria/)});
