import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {generateKeyPairSync,sign,webcrypto}from'node:crypto';
if(!globalThis.crypto)globalThis.crypto=webcrypto;if(!globalThis.btoa)globalThis.btoa=value=>Buffer.from(value,'binary').toString('base64');if(!globalThis.atob)globalThis.atob=value=>Buffer.from(value,'base64').toString('binary');
const {testables}=await import('../../src/admin/worker.js'),origin='https://imoveis.londrinense.net',clientId='google-client.apps.googleusercontent.com';
const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048});const jwk=publicKey.export({format:'jwk'});Object.assign(jwk,{kid:'test-key',alg:'RS256',use:'sig'});
const base64url=value=>Buffer.from(typeof value==='string'?value:JSON.stringify(value)).toString('base64url');
function token(overrides={}){const header=base64url({alg:'RS256',kid:'test-key',typ:'JWT'}),payload=base64url({iss:'https://accounts.google.com',aud:clientId,sub:'google-subject',email:'londrinense.net@gmail.com',email_verified:true,name:'Google Name',picture:'https://example.test/photo.jpg',exp:Math.floor(Date.now()/1000)+600,...overrides}),signature=sign('RSA-SHA256',Buffer.from(`${header}.${payload}`),privateKey).toString('base64url');return`${header}.${payload}.${signature}`}
const env=()=>({SESSION_SECRET:'s'.repeat(48),GOOGLE_CLIENT_ID:clientId,ADMIN_ORIGIN:origin,GITHUB_OWNER:'o',GITHUB_REPO:'r',GITHUB_BRANCH:'main',GITHUB_ADMIN_TOKEN:'x'});
const request=(path,method='GET',data,headers={})=>new Request(`https://api.example${path}`,{method,headers:{origin,...headers,...(data?{'content-type':'application/json'}:{})},body:data&&JSON.stringify(data)});
let capturedWrites=[];function mockGithub(records={}){capturedWrites=[];globalThis.fetch=async(url,options={})=>{if(String(url).includes('/branches/'))return Response.json({name:'main'});if(options.method==='DELETE')return new Response(null,{status:204});if(options.method==='PUT'){capturedWrites.push({url:String(url),body:JSON.parse(options.body)});return Response.json({content:{sha:'new-sha'}})}if(String(url).includes('googleapis.com'))return Response.json({keys:[jwk]});const path=decodeURIComponent(String(url));if(path.includes('/contents/private/admins?'))return Response.json(Object.values(records).filter(x=>x.kind==='admin').map(x=>({type:'file',name:`${x.data.id}.json`})));if(path.includes('/contents/private/clientes?'))return Response.json(Object.values(records).filter(x=>x.kind==='client').map(x=>({type:'dir',name:x.data.id})));for(const record of Object.values(records))if(path.includes(`/contents/${record.path}?`))return Response.json({content:Buffer.from(JSON.stringify(record.data)).toString('base64'),sha:'sha'});return Response.json({message:'not found'},{status:404})}}
async function googleLogin(email='londrinense.net@gmail.com',overrides={}){return testables.handle(request('/api/auth/google','POST',{credential:token({email,...overrides})}),env())}
test('config expõe somente o Client ID público',async()=>{const response=await testables.handle(request('/api/config'),env());assert.deepEqual(await response.json(),{googleClientId:clientId})});
test('token Google válido do MASTER retorna 200, MASTER oficial e sessão segura',async()=>{mockGithub();const response=await googleLogin();assert.equal(response.status,200);assert.deepEqual((await response.json()).usuario,{id:'MASTER',email:'londrinense.net@gmail.com',nome:'SUPERADMIN',role:'MASTER'});for(const flag of ['HttpOnly','Secure','SameSite=Strict','Path=/'])assert.match(response.headers.get('set-cookie'),new RegExp(flag));assert.doesNotMatch(response.headers.get('set-cookie'),new RegExp(token().split('.')[0]))});
test('email_verified falso, audience incorreto, expiração e token inválido são rejeitados',async()=>{mockGithub();for(const credential of[token({email_verified:false}),token({aud:'outro'}),token({exp:1}),'inválido']){const response=await testables.handle(request('/api/auth/google','POST',{credential}),env());assert.equal(response.status,401)}});
test('conta Google não cadastrada recebe conta_nao_autorizada',async()=>{mockGithub();const response=await googleLogin('unknown@example.com');assert.equal(response.status,403);assert.deepEqual(await response.json(),{error:'conta_nao_autorizada'})});
test('ADMIN cadastrado recebe role ADMIN',async()=>{mockGithub({admin:{kind:'admin',path:'private/admins/admin-0002.json',data:{id:'admin-0002',nome:'João',email:'joao@gmail.com',role:'ADMIN',ativo:true}}});const response=await googleLogin('joao@gmail.com');assert.equal(response.status,200);assert.equal((await response.json()).usuario.role,'ADMIN')});
test('CLIENTE cadastrado recebe cliente_id correto',async()=>{mockGithub({client:{kind:'client',path:'private/clientes/00017/cliente.json',data:{id:'00017',cliente_id:'00017',nome:'Imobiliária X',email_login:'cliente@gmail.com',ativo:true}}});const response=await googleLogin('cliente@gmail.com');assert.equal(response.status,200);assert.deepEqual((await response.json()).usuario,{id:'00017',email:'cliente@gmail.com',nome:'Imobiliária X',role:'CLIENTE',cliente_id:'00017'})});
test('MASTER não pode ser excluído, desativado nem rebaixado',async()=>{mockGithub();const identity={sub:'google-subject',email:'londrinense.net@gmail.com',role:'MASTER',nome:'SUPERADMIN'},session=await testables.session(identity,env().SESSION_SECRET),headers={cookie:`session=${session}`};for(const [path,method,data]of[['/api/administradores/MASTER','DELETE',{}],['/api/administradores/master/disable','POST',{}],['/api/administradores/MASTER','PUT',{nome:'SUPERADMIN',email:'londrinense.net@gmail.com',role:'ADMIN',ativo:true}]])assert.equal((await testables.handle(request(path,method,data,headers),env())).status,409)});
test('logout remove a sessão local',async()=>{const response=await testables.handle(request('/api/logout','POST',{}),env());assert.equal(response.status,200);assert.match(response.headers.get('set-cookie'),/Max-Age=0/)});
test('runtime não contém autenticação administrativa local nem exige Client Secret',()=>{const source=fs.readFileSync('src/admin/worker.js','utf8'),publicFiles=fs.readdirSync('public/painel',{recursive:true}).filter(name=>/\.(?:html|js)$/.test(name)).map(name=>fs.readFileSync(`public/painel/${name}`,'utf8')).join('\n');for(const obsolete of['SUPERADMIN_'+'USER','SUPERADMIN_'+'PASSWORD_HASH','mustChange'+'Password','password'+'Hash','PBK'+'DF2','GOOGLE_'+'CLIENT_SECRET','/api/login'])assert.doesNotMatch(source,new RegExp(obsolete));assert.doesNotMatch(publicFiles,/type=["']password|Senha temporária|Alterar senha/)});
const validClient={nome:'Imobiliária Modelo',tipo:'imobiliaria',status:'ativo',ativo:true,email_login:' CLIENTE@Example.COM ',cpf_cnpj:'529.982.247-25',uf:'PR',cidade:'Londrina',cep:'86000-000',site:'imobiliaria.com.br',imagem_tipo:'logo',imagem_url:'https://cdn.example/logo.png',feed_url:'http://crm.example/feed.xml?token=privado',feed_formato:'xml',feed_ativo:true,celular_administrativo:'+55 (43) 99999-1111',whatsapp_administrativo:'+351 912 345 678'};
test('cadastro normaliza documento, CEP, e-mail, site e preserva imagem externa',()=>{const client=testables.clientPayload(validClient,'00001');assert.equal(client.id,'00001');assert.equal(client.cliente_id,'00001');assert.equal(client.email_login,'cliente@example.com');assert.equal(client.cpf_cnpj,'52998224725');assert.equal(client.cep,'86000000');assert.equal(client.site,'https://imobiliaria.com.br/');assert.equal(client.imagem_tipo,'logo');assert.equal(client.imagem_url,'https://cdn.example/logo.png');assert.equal(client.celular_administrativo,'+5543999991111');assert.equal(client.whatsapp_administrativo,'+351912345678')});
test('imagem externa funciona sem tipo de imagem',()=>{const {imagem_tipo,...withoutType}=validClient,client=testables.clientPayload(withoutType,'00001');assert.equal(client.imagem_url,'https://cdn.example/logo.png');assert.equal(client.imagem_tipo,undefined)});
test('referência pertence ao cadastro privado do cliente',()=>{const client=testables.clientPayload({...validClient,referencia:'Próximo ao lago'},'00001');assert.equal(client.referencia,'Próximo ao lago')});
test('CPF e CNPJ válidos são aceitos e formatos inválidos rejeitados',()=>{assert.equal(testables.validDocument('529.982.247-25'),true);assert.equal(testables.validDocument('04.252.011/0001-10'),true);for(const invalid of['123','111.111.111-11','04.252.011/0001-11'])assert.equal(testables.validDocument(invalid),false)});
test('UF e tipo de imagem usam listas fechadas',()=>{assert.throws(()=>testables.clientPayload({...validClient,uf:'XX'},'00001'),/Selecione uma UF/);assert.throws(()=>testables.clientPayload({...validClient,imagem_tipo:'ambas'},'00001'),/Tipo de imagem/)});
test('site recebe HTTPS sem duplicar protocolo e feed aceita HTTP ou HTTPS',()=>{assert.equal(testables.normalizedUrl('imobiliaria.com.br'),'https://imobiliaria.com.br/');assert.equal(testables.normalizedUrl('https://imobiliaria.com.br'),'https://imobiliaria.com.br/');assert.equal(testables.safeFeed({feed_url:'http://crm.example/feed.json?token=x',formato:'json'}).feed_url,'http://crm.example/feed.json?token=x');assert.equal(testables.safeFeed({feed_url:'https://crm.example/feed.xml',formato:'xml'}).formato,'xml')});
test('ID informado no payload não substitui o ID permanente da rota',()=>{const client=testables.clientPayload({...validClient,id:'99999',cliente_id:'99999'},'00017');assert.equal(client.id,'00017');assert.equal(client.cliente_id,'00017')});
test('campos obrigatórios produzem mensagens claras',()=>{assert.throws(()=>testables.clientPayload({...validClient,email_login:''},'00001'),/Informe o e-mail/);assert.throws(()=>testables.clientPayload({...validClient,cpf_cnpj:''},'00001'),/CPF\/CNPJ inválido/);assert.throws(()=>testables.safeFeed({feed_url:''}),/Informe a URL do feed/) });
test('cria cliente com próximo ID sequencial automático e contador monotônico',async()=>{mockGithub({client:{kind:'client',path:'private/clientes/00002/cliente.json',data:{id:'00002',nome:'Existente',email_login:'existente@example.com',ativo:true}}});const identity={sub:'google-subject',email:'londrinense.net@gmail.com',role:'MASTER',nome:'SUPERADMIN'},signed=await testables.session(identity,env().SESSION_SECRET),response=await testables.handle(request('/api/clientes','POST',validClient,{cookie:`session=${signed}`}),env());assert.equal(response.status,201);assert.equal((await response.json()).id,'00003');assert.ok(capturedWrites.some(write=>write.url.includes('/private/clientes/.sequence.json')));assert.ok(capturedWrites.some(write=>write.url.includes('/private/clientes/00003/cliente.json')));assert.ok(capturedWrites.some(write=>write.url.includes('/private/clientes/00003/feed.json')))});
test('previsão do próximo ID tem cinco dígitos, respeita o contador e não o reserva',async()=>{mockGithub({sequence:{path:'private/clientes/.sequence.json',data:{last_id:16}}});const identity={sub:'google-subject',email:'londrinense.net@gmail.com',role:'MASTER',nome:'SUPERADMIN'},signed=await testables.session(identity,env().SESSION_SECRET),response=await testables.handle(request('/api/clientes/proximo-id','GET',undefined,{cookie:`session=${signed}`}),env());assert.equal(response.status,200);assert.deepEqual(await response.json(),{id:'00017'});assert.equal(capturedWrites.length,0)});
test('edição persiste contatos e preserva dados legados e provider oculto',async()=>{mockGithub({client:{kind:'client',path:'private/clientes/00017/cliente.json',data:{...validClient,id:'00017',cliente_id:'00017',descricao_publica:'Legado'}},feed:{path:'private/clientes/00017/feed.json',data:{cliente_id:'00017',feed_url:validClient.feed_url,origem:'crm-legado',formato:'xml',ativo:true}}});const identity={sub:'google-subject',email:'londrinense.net@gmail.com',role:'MASTER',nome:'SUPERADMIN'},signed=await testables.session(identity,env().SESSION_SECRET),{imagem_tipo,...payload}=validClient;delete payload.feed_origem;const response=await testables.handle(request('/api/clientes/00017','PUT',{...payload,id:'99999',cliente_id:'99999',referencia:'Portão azul'},{cookie:`session=${signed}`}),env());assert.equal(response.status,200);const write=capturedWrites.find(item=>item.url.includes('/private/clientes/00017/cliente.json')),saved=JSON.parse(Buffer.from(write.body.content,'base64').toString()),feedWrite=capturedWrites.find(item=>item.url.includes('/private/clientes/00017/feed.json')),savedFeed=JSON.parse(Buffer.from(feedWrite.body.content,'base64').toString());assert.equal(saved.id,'00017');assert.equal(saved.cliente_id,'00017');assert.equal(saved.referencia,'Portão azul');assert.equal(saved.descricao_publica,'Legado');assert.equal(saved.imagem_tipo,'logo');assert.equal(saved.celular_administrativo,'+5543999991111');assert.equal(saved.whatsapp_administrativo,'+351912345678');assert.equal(savedFeed.origem,'crm-legado')});
test('contatos administrativos retornam para edição pela API privada',async()=>{mockGithub({client:{kind:'client',path:'private/clientes/00017/cliente.json',data:{...validClient,id:'00017',cliente_id:'00017'}}});const identity={sub:'google-subject',email:'londrinense.net@gmail.com',role:'MASTER',nome:'SUPERADMIN'},signed=await testables.session(identity,env().SESSION_SECRET),response=await testables.handle(request('/api/clientes/00017','GET',undefined,{cookie:`session=${signed}`}),env()),client=await response.json();assert.equal(response.status,200);assert.equal(client.celular_administrativo,validClient.celular_administrativo);assert.equal(client.whatsapp_administrativo,validClient.whatsapp_administrativo)});
test('e-mail de acesso duplicado entre clientes é rejeitado',async()=>{mockGithub({client:{kind:'client',path:'private/clientes/00002/cliente.json',data:{id:'00002',nome:'Existente',email_login:'cliente@example.com',ativo:true}}});const identity={sub:'google-subject',email:'londrinense.net@gmail.com',role:'MASTER',nome:'SUPERADMIN'},signed=await testables.session(identity,env().SESSION_SECRET),response=await testables.handle(request('/api/clientes','POST',validClient,{cookie:`session=${signed}`}),env());assert.equal(response.status,409);assert.match((await response.json()).erro,/e-mail de acesso/);assert.equal(capturedWrites.length,0)});

test('formulário mantém matriz de duas colunas com observações como única exceção',()=>{const source=fs.readFileSync('public/painel/modulos/cliente-formulario.js','utf8'),css=fs.readFileSync('public/painel/painel.css','utf8');assert.match(source,/ID do cliente[^\n]+readonly aria-readonly="true"/);assert.match(source,/api\('\/clientes\/proximo-id'\)/);for(const required of['Referência','Celular administrativo','WhatsApp administrativo','URL Foto do Corretor / Logomarca','Formato do feed','Feed ativo','id="image-preview"','<label>Status'])assert.match(source,new RegExp(required));for(const removed of['Tipo de imagem','name="imagem_tipo"','Limpar escolha','Descrição pública','name="descricao_publica"','class="wide-input"','class="half"'])assert.doesNotMatch(source,new RegExp(removed));assert.match(source,/class="private-notes">Observações privadas/);assert.equal((source.match(/class="private-notes"/g)||[]).length,1);assert.match(css,/\.form-grid\{display:grid;grid-template-columns:repeat\(2,minmax\(0,1fr\)\);gap:1rem\}/);assert.match(css,/\.form-grid \.wide,\.form-grid \.private-notes\{grid-column:1\/-1\}/);assert.match(css,/\.form-section\+\.form-section[^}]+margin-top:1\.5rem/);assert.match(css,/@media\(max-width:560px\)\{\.cards,\.form-grid\{grid-template-columns:1fr\}/)});

test('hierarquia e autorização central protegem operações',()=>{const master={id:'MASTER',role:'MASTER'},superadmin={id:'A01',role:'SUPERADMIN'},admin={id:'A02',role:'ADMIN',permissoes:{incluir:true,editar:false,excluir:false}};assert.equal(testables.isProtectedMaster(master),true);assert.equal(testables.canManageAdmin(superadmin,master),false);assert.equal(testables.canManageAdmin(superadmin,admin),true);assert.equal(testables.canManageAdmin(superadmin,{id:'A03',role:'SUPERADMIN'}),false);assert.equal(testables.hasPermission(admin,'incluir'),true);assert.equal(testables.hasPermission(admin,'editar'),false);assert.equal(testables.hasPermission(superadmin,'excluir'),true)});
test('IDs administrativos são A01-A99, monotônicos e não incluem MASTER',async()=>{mockGithub({admin:{kind:'admin',path:'private/admins/A02.json',data:{id:'A02',nome:'Atual',email:'atual@example.com',role:'ADMIN',ativo:true}},sequence:{path:'private/admins/.sequence.json',data:{last_id:7}}});assert.equal(await testables.nextAdminId(env(),{reserve:false}),'A08');assert.equal(capturedWrites.length,0);assert.equal(await testables.nextAdminId(env()),'A08');assert.ok(capturedWrites.some(write=>write.url.includes('/private/admins/.sequence.json')))});
test('limite de 99 administradores é explícito',async()=>{mockGithub({sequence:{path:'private/admins/.sequence.json',data:{last_id:99}}});await assert.rejects(()=>testables.nextAdminId(env()),/Limite de 99 administradores atingido/)});
test('CRM/origem aceita texto livre e vazio sem valor genérico automático',()=>{for(const origem of ['OLX','ZAP','Viva Real','Kenlo','Sistema próprio',''])assert.equal(testables.safeFeed({feed_url:'https://feed.example/data.xml',formato:'xml',origem}).origem,origem)});
test('novo administrador ignora ID arbitrário e persiste foto e permissões',async()=>{mockGithub();const identity={sub:'google-subject',email:'londrinense.net@gmail.com',role:'MASTER',nome:'SUPERADMIN'},signed=await testables.session(identity,env().SESSION_SECRET),response=await testables.handle(request('/api/administradores','POST',{id:'EVIL',nome:'Maria',email:'maria@example.com',role:'ADMIN',ativo:true,foto_url:'https://example.com/maria.jpg',permissoes:{incluir:true,editar:false,excluir:true}},{cookie:`session=${signed}`}),env());assert.equal(response.status,201);assert.equal((await response.json()).id,'A01');const write=capturedWrites.find(item=>item.url.includes('/private/admins/A01.json')),saved=JSON.parse(Buffer.from(write.body.content,'base64'));assert.equal(saved.foto_url,'https://example.com/maria.jpg');assert.deepEqual(saved.permissoes,{incluir:true,editar:false,excluir:true})});
test('UI não oferece MASTER, não renderiza ações destrutivas protegidas e mantém menu alfabético',()=>{const html=fs.readFileSync('public/painel/index.html','utf8'),admins=fs.readFileSync('public/painel/modulos/administradores.js','utf8'),labels=[...html.matchAll(/data-route="[^"]+" title="([^"]+)"/g)].map(x=>x[1]);assert.deepEqual(labels,['Administradores','Clientes','Configurações','Dashboard','Minha conta','Sincronizações','Diagnóstico']);assert.doesNotMatch(admins,/<option value="MASTER"/);assert.match(admins,/a\.protegido\?'<span class="protected"/);assert.match(admins,/form\.role\.value!==['"]ADMIN['"]/);assert.match(admins,/URL da foto/)});
