import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {generateKeyPairSync,sign,webcrypto}from'node:crypto';
if(!globalThis.crypto)globalThis.crypto=webcrypto;if(!globalThis.btoa)globalThis.btoa=value=>Buffer.from(value,'binary').toString('base64');if(!globalThis.atob)globalThis.atob=value=>Buffer.from(value,'base64').toString('binary');
const {testables}=await import('../../src/admin/worker.js'),origin='https://imoveis.londrinense.net',clientId='google-client.apps.googleusercontent.com';
const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048});const jwk=publicKey.export({format:'jwk'});Object.assign(jwk,{kid:'test-key',alg:'RS256',use:'sig'});
const base64url=value=>Buffer.from(typeof value==='string'?value:JSON.stringify(value)).toString('base64url');
function token(overrides={}){const header=base64url({alg:'RS256',kid:'test-key',typ:'JWT'}),payload=base64url({iss:'https://accounts.google.com',aud:clientId,sub:'google-subject',email:'londrinense.net@gmail.com',email_verified:true,name:'Google Name',picture:'https://example.test/photo.jpg',exp:Math.floor(Date.now()/1000)+600,...overrides}),signature=sign('RSA-SHA256',Buffer.from(`${header}.${payload}`),privateKey).toString('base64url');return`${header}.${payload}.${signature}`}
const env=()=>({SESSION_SECRET:'s'.repeat(48),GOOGLE_CLIENT_ID:clientId,ADMIN_ORIGIN:origin,GITHUB_OWNER:'o',GITHUB_REPO:'r',GITHUB_BRANCH:'main',GITHUB_ADMIN_TOKEN:'x'});
const request=(path,method='GET',data,headers={})=>new Request(`https://api.example${path}`,{method,headers:{origin,...headers,...(data?{'content-type':'application/json'}:{})},body:data&&JSON.stringify(data)});
function mockGithub(records={}){globalThis.fetch=async url=>{if(String(url).includes('googleapis.com'))return Response.json({keys:[jwk]});const path=decodeURIComponent(String(url));if(path.includes('/contents/private/admins?'))return Response.json(Object.values(records).filter(x=>x.kind==='admin').map(x=>({type:'file',name:`${x.data.id}.json`})));if(path.includes('/contents/private/clientes?'))return Response.json(Object.values(records).filter(x=>x.kind==='client').map(x=>({type:'dir',name:x.data.id})));for(const record of Object.values(records))if(path.includes(`/contents/${record.path}?`))return Response.json({content:Buffer.from(JSON.stringify(record.data)).toString('base64'),sha:'sha'});return Response.json({message:'not found'},{status:404})}}
async function googleLogin(email='londrinense.net@gmail.com',overrides={}){return testables.handle(request('/api/auth/google','POST',{credential:token({email,...overrides})}),env())}
test('config expõe somente o Client ID público',async()=>{const response=await testables.handle(request('/api/config'),env());assert.deepEqual(await response.json(),{googleClientId:clientId})});
test('token Google válido do MASTER retorna 200, MASTER oficial e sessão segura',async()=>{mockGithub();const response=await googleLogin();assert.equal(response.status,200);assert.deepEqual((await response.json()).usuario,{id:'master',email:'londrinense.net@gmail.com',nome:'SUPERADMIN',role:'MASTER'});for(const flag of ['HttpOnly','Secure','SameSite=Strict','Path=/'])assert.match(response.headers.get('set-cookie'),new RegExp(flag));assert.doesNotMatch(response.headers.get('set-cookie'),new RegExp(token().split('.')[0]))});
test('email_verified falso, audience incorreto, expiração e token inválido são rejeitados',async()=>{mockGithub();for(const credential of[token({email_verified:false}),token({aud:'outro'}),token({exp:1}),'inválido']){const response=await testables.handle(request('/api/auth/google','POST',{credential}),env());assert.equal(response.status,401)}});
test('conta Google não cadastrada recebe conta_nao_autorizada',async()=>{mockGithub();const response=await googleLogin('unknown@example.com');assert.equal(response.status,403);assert.deepEqual(await response.json(),{error:'conta_nao_autorizada'})});
test('ADMIN cadastrado recebe role ADMIN',async()=>{mockGithub({admin:{kind:'admin',path:'private/admins/admin-0002.json',data:{id:'admin-0002',nome:'João',email:'joao@gmail.com',role:'ADMIN',ativo:true}}});const response=await googleLogin('joao@gmail.com');assert.equal(response.status,200);assert.equal((await response.json()).usuario.role,'ADMIN')});
test('CLIENTE cadastrado recebe cliente_id correto',async()=>{mockGithub({client:{kind:'client',path:'private/clientes/00017/cliente.json',data:{id:'00017',cliente_id:'00017',nome:'Imobiliária X',email_login:'cliente@gmail.com',ativo:true}}});const response=await googleLogin('cliente@gmail.com');assert.equal(response.status,200);assert.deepEqual((await response.json()).usuario,{id:'00017',email:'cliente@gmail.com',nome:'Imobiliária X',role:'CLIENTE',cliente_id:'00017'})});
test('MASTER não pode ser excluído, desativado nem rebaixado',async()=>{mockGithub();const identity={sub:'google-subject',email:'londrinense.net@gmail.com',role:'MASTER',nome:'SUPERADMIN'},session=await testables.session(identity,env().SESSION_SECRET),headers={cookie:`session=${session}`};for(const [path,method,data]of[['/api/administradores/master','DELETE',{}],['/api/administradores/master/disable','POST',{}],['/api/administradores/master','PUT',{nome:'SUPERADMIN',email:'londrinense.net@gmail.com',role:'ADMIN',ativo:true}]])assert.equal((await testables.handle(request(path,method,data,headers),env())).status,409)});
test('logout remove a sessão local',async()=>{const response=await testables.handle(request('/api/logout','POST',{}),env());assert.equal(response.status,200);assert.match(response.headers.get('set-cookie'),/Max-Age=0/)});
test('runtime não contém autenticação administrativa local nem exige Client Secret',()=>{const source=fs.readFileSync('src/admin/worker.js','utf8'),publicFiles=fs.readdirSync('public/painel',{recursive:true}).filter(name=>/\.(?:html|js)$/.test(name)).map(name=>fs.readFileSync(`public/painel/${name}`,'utf8')).join('\n');for(const obsolete of['SUPERADMIN_'+'USER','SUPERADMIN_'+'PASSWORD_HASH','mustChange'+'Password','password'+'Hash','PBK'+'DF2','GOOGLE_'+'CLIENT_SECRET','/api/login'])assert.doesNotMatch(source,new RegExp(obsolete));assert.doesNotMatch(publicFiles,/type=["']password|Senha temporária|Alterar senha/)});
