const HEADERS={"cache-control":"no-store","content-type":"application/json; charset=utf-8","x-content-type-options":"nosniff"};
const LIMIT=16_384, ITERATIONS=310_000, SESSION_SECONDS=3600;
const attempts=new Map();
const bytes=v=>new TextEncoder().encode(v);
const b64=v=>btoa(String.fromCharCode(...v)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");
const unb64=v=>atob(v.replaceAll("-","+").replaceAll("_","/").padEnd(Math.ceil(v.length/4)*4,"="));
const same=(a,b)=>{if(typeof a!=="string"||typeof b!=="string"||a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0};
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{...HEADERS,...headers}});
const validId=id=>typeof id==="string"&&/^[a-z0-9][a-z0-9-]{2,39}$/.test(id);
const cookie=token=>`session=${token}; Path=/; Max-Age=${SESSION_SECONDS}; HttpOnly; Secure; SameSite=Strict`;
const clearCookie=()=>"session=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict";

async function body(request){const raw=await request.text();if(bytes(raw).length>LIMIT)throw new RangeError("payload");try{const value=JSON.parse(raw);if(!value||Array.isArray(value)||typeof value!=="object")throw 0;return value}catch{throw new SyntaxError("json")}}
async function mac(value,secret){const key=await crypto.subtle.importKey("raw",bytes(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64(new Uint8Array(await crypto.subtle.sign("HMAC",key,bytes(value))))}
async function session(user,role,secret,ttl=SESSION_SECONDS){const payload=b64(bytes(JSON.stringify({sub:user,role,exp:Math.floor(Date.now()/1000)+ttl})));return `${payload}.${await mac(payload,secret)}`}
async function authenticate(request,env){const token=(request.headers.get("cookie")||"").match(/(?:^|;\s*)session=([^;]+)/)?.[1];if(!token)return null;const [payload,signature]=token.split(".");if(!same(signature||"",await mac(payload||"",env.SESSION_SECRET)))return null;try{const data=JSON.parse(unb64(payload));return data.exp>Date.now()/1000&&["superadmin","cliente"].includes(data.role)?data:null}catch{return null}}
async function passwordHash(password,salt,iterations=ITERATIONS){const material=await crypto.subtle.importKey("raw",bytes(password),"PBKDF2",false,["deriveBits"]);return b64(new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:bytes(salt),iterations},material,256)))}
async function encodedPasswordHash(password){const salt=b64(crypto.getRandomValues(new Uint8Array(16)));return `pbkdf2-sha256$${ITERATIONS}$${salt}$${await passwordHash(password,salt)}`}
async function verifyPassword(password,stored){const [scheme,cost,salt,hash]=String(stored||"").split("$");return scheme==="pbkdf2-sha256"&&cost===String(ITERATIONS)&&/^[\w-]{16,64}$/.test(salt||"")&&/^[\w-]{40,64}$/.test(hash||"")&&same(await passwordHash(password,salt),hash)}
async function github(env,path,options={}){const response=await fetch(`https://api.github.com/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}${path}`,{...options,headers:{accept:"application/vnd.github+json",authorization:`Bearer ${env.GITHUB_ADMIN_TOKEN}`,"x-github-api-version":"2022-11-28","user-agent":"portal-londrinense-admin",...(options.headers||{})}});if(!response.ok)throw new Error(`GitHub ${response.status}`);return response.status===204?null:response.json()}
const decodeFile=result=>JSON.parse(decodeURIComponent(escape(atob(result.content.replace(/\s/g,"")))));
async function file(env,path){try{const result=await github(env,`/contents/${path}?ref=${encodeURIComponent(env.GITHUB_BRANCH)}`);return{data:decodeFile(result),sha:result.sha}}catch{return{data:null,sha:null}}}
async function list(env,path){try{const result=await github(env,`/contents/${path}?ref=${encodeURIComponent(env.GITHUB_BRANCH)}`);return Array.isArray(result)?result:[]}catch{return[]}}
async function save(env,path,value,sha){const payload={message:`admin: atualiza ${path.split("/").at(-1)}`,branch:env.GITHUB_BRANCH,content:btoa(unescape(encodeURIComponent(`${JSON.stringify(value,null,2)}\n`)))};if(sha)payload.sha=sha;return github(env,`/contents/${path}`,{method:"PUT",body:JSON.stringify(payload)})}
async function clients(env){const dirs=await list(env,"private/clientes");const values=await Promise.all(dirs.filter(x=>x.type==="dir"&&validId(x.name)).map(async x=>{const client=(await file(env,`private/clientes/${x.name}/cliente.json`)).data;if(!client)return null;const feed=(await file(env,`private/clientes/${x.name}/feed.json`)).data;return{...client,feed:{configurado:!!feed,ativo:!!feed?.ativo,status:feed?.status||(!feed?"ausente":"nunca_sincronizado")}}}));return values.filter(Boolean)}
function clientPayload(value,id=value.id){const allowed=["nome","tipo","creci","status","ativo","razao_social","documento","responsavel","email_administrativo","telefone_administrativo","observacoes","nome_publico","descricao","telefone_publico","whatsapp","email_publico","site","logo","endereco_publico","publicar_endereco","cidade","uf","regioes"];
 if(!validId(id)||typeof value.nome!=="string"||!value.nome.trim()||value.nome.length>160||!["imobiliaria","corretor"].includes(value.tipo)||Object.keys(value).some(k=>!allowed.includes(k)&&k!=="id"))throw new TypeError("Cliente inválido");
 return Object.fromEntries([["id",id],...allowed.map(k=>[k,value[k]]).filter(([,v])=>v!==undefined)]);
}
const can=(auth,id)=>auth.role==="superadmin"||auth.sub===id;
function safeFeed(value){let url;try{url=new URL(value.feed_url)}catch{throw new TypeError("Feed inválido")};const host=url.hostname.toLowerCase();if(url.protocol!=="https:"||url.username||url.password||url.hash||!host||host==="localhost"||host.endsWith(".local")||/^127\.|^10\.|^192\.168\.|^169\.254\.|^172\.(1[6-9]|2\d|3[01])\./.test(host)||host==="[::1]")throw new TypeError("Feed inválido");return{feed_url:url.href,origem:String(value.origem||"generico").slice(0,50),formato:"xml",ativo:value.ativo!==false}}
async function dispatch(env,workflow,inputs){await github(env,`/actions/workflows/${workflow}/dispatches`,{method:"POST",body:JSON.stringify({ref:env.GITHUB_BRANCH,inputs})});return json({status:"solicitacao_enviada",mensagem:"Solicitação enviada; acompanhe o workflow para obter o resultado."},202)}

async function handle(request,env){try{const url=new URL(request.url);if(!url.pathname.startsWith("/api/"))return json({erro:"Rota inexistente"},404);if(url.protocol!=="https:")return json({erro:"HTTPS obrigatório"},400);if(request.headers.get("origin")!==env.ADMIN_ORIGIN)return json({erro:"Origem não autorizada"},403);if(request.method==="OPTIONS")return new Response(null,{status:204,headers:{allow:"GET, POST, PUT, OPTIONS","access-control-allow-origin":env.ADMIN_ORIGIN,"access-control-allow-credentials":"true","access-control-allow-headers":"content-type",vary:"Origin"}});if(["POST","PUT"].includes(request.method)&&(request.headers.get("content-type")||"").split(";")[0]!=="application/json")return json({erro:"Conteúdo inválido"},415);if(Number(request.headers.get("content-length")||0)>LIMIT)return json({erro:"Conteúdo excede o limite"},413);
 if(url.pathname==="/api/login"&&request.method==="POST"){const key=request.headers.get("cf-connecting-ip")||"desconhecido", data=await body(request), recent=(attempts.get(key)||[]).filter(x=>Date.now()-x<900000);let role=null;if(data.usuario==="ADMIN"&&data.senha==="TESTE")role="superadmin";else if(recent.length>=10)return json({erro:"Muitas tentativas"},429,{"retry-after":String(Math.ceil((recent[0]+900000-Date.now())/1000))});else if(data.usuario===env.SUPERADMIN_USER&&await verifyPassword(data.senha,env.SUPERADMIN_PASSWORD_HASH))role="superadmin";else if(validId(data.usuario)){const account=(await file(env,`private/clientes/${data.usuario}/acesso.json`)).data;if(account?.ativo&&await verifyPassword(data.senha,account.senha_hash))role="cliente"}if(!role){attempts.set(key,[...recent,Date.now()]);return json({erro:"Credenciais inválidas"},401)}attempts.delete(key);return json({papel:role,troca_senha_obrigatoria:false},200,{"set-cookie":cookie(await session(data.usuario,role,env.SESSION_SECRET))})}
 if(url.pathname==="/api/logout"&&request.method==="POST")return json({ok:true},200,{"set-cookie":clearCookie()});
 const auth=await authenticate(request,env);if(!auth)return json({erro:"Não autenticado"},401);
 if(url.pathname==="/api/sessao"&&request.method==="GET")return json({usuario:auth.sub,nome:auth.sub,papel:auth.role,permissoes:auth.role==="superadmin"?["administracao_total"]:["propria_conta"]});
 if(url.pathname==="/api/dashboard"&&request.method==="GET"){const all=await clients(env);const total=status=>all.filter(x=>(x.status||(x.ativo===false?"inativo":"ativo"))===status).length;return json({clientes:{total:all.length,ativos:total("ativo"),inativos:total("inativo"),suspensos:total("suspenso")},feeds:{total:all.filter(x=>x.feed.configurado).length,ativos:all.filter(x=>x.feed.ativo).length,com_erro:all.filter(x=>x.feed.status==="erro").length,nunca_sincronizados:all.filter(x=>x.feed.status==="nunca_sincronizado").length},imoveis:{publicados:0,rejeitados:0,por_finalidade:{},por_categoria:{}},sincronizacao:{ultima:null,proxima:null,em_execucao:0,falhas_recentes:[]},alteracoes_recentes:[]})}
 if(url.pathname==="/api/clientes"&&request.method==="GET"){let all=await clients(env);if(auth.role!=="superadmin")all=all.filter(x=>x.id===auth.sub);const q=(url.searchParams.get("q")||"").toLowerCase(),status=url.searchParams.get("status"),tipo=url.searchParams.get("tipo"),feed=url.searchParams.get("feed");all=all.filter(x=>(!q||[x.id,x.nome,x.razao_social,x.documento,x.responsavel,x.creci,x.cidade,x.email_administrativo,x.telefone_administrativo].some(v=>String(v||"").toLowerCase().includes(q)))&&(!status||(x.status||(x.ativo===false?"inativo":"ativo"))===status)&&(!tipo||x.tipo===tipo)&&(!feed||(feed==="com"?x.feed.configurado:!x.feed.configurado)));all.sort((a,b)=>String(a.nome).localeCompare(String(b.nome),"pt-BR"));return json({itens:all,total:all.length})}
 if(url.pathname==="/api/clientes"&&["POST","PUT"].includes(request.method)){if(auth.role!=="superadmin")return json({erro:"Proibido"},403);const data=await body(request), value=clientPayload(data);const prior=await file(env,`private/clientes/${value.id}/cliente.json`);if(request.method==="POST"&&prior.data)return json({erro:"ID já cadastrado"},409);await save(env,`private/clientes/${value.id}/cliente.json`,value,prior.sha);return json({salvo:true,id:value.id},request.method==="POST"?201:200)}
 if(url.pathname==="/api/sincronizar"&&request.method==="POST"){if(auth.role!=="superadmin")return json({erro:"Proibido"},403);return dispatch(env,"sincronizar.yml",{confirmar:"SINCRONIZAR"})}
 const match=url.pathname.match(/^\/api\/clientes\/([a-z0-9-]+)(?:\/(feed|sincronizar|ativar|desativar|suspender|exportar))?(?:\/(testar))?$/);if(match){const[,id,action,sub]=match;if(!validId(id)||!can(auth,id))return json({erro:"Proibido"},403);const current=await file(env,`private/clientes/${id}/cliente.json`);
  if(!action&&request.method==="GET"){if(!current.data)return json({erro:"Cliente inexistente"},404);const feed=(await file(env,`private/clientes/${id}/feed.json`)).data;return json({...current.data,feed:feed?{...feed,feed_url:undefined,configurado:true}:{configurado:false}})}
  if(!action&&request.method==="PUT"){if(!current.data)return json({erro:"Cliente inexistente"},404);if(auth.role!=="superadmin")return json({erro:"Proibido"},403);const value=clientPayload(await body(request),id);await save(env,`private/clientes/${id}/cliente.json`,value,current.sha);return json({salvo:true,id})}
  if(["ativar","desativar","suspender"].includes(action)&&request.method==="POST"){if(auth.role!=="superadmin")return json({erro:"Proibido"},403);const status=action==="ativar"?"ativo":action==="desativar"?"inativo":"suspenso";await save(env,`private/clientes/${id}/cliente.json`,{...current.data,status,ativo:status==="ativo"},current.sha);return json({salvo:true,status})}
  if(action==="exportar"&&request.method==="GET"){const {observacoes,...safe}=current.data;return json(safe,200,{"content-disposition":`attachment; filename="cliente-${id}.json"`})}
  if(action==="sincronizar"&&request.method==="POST")return dispatch(env,"sincronizar-cliente.yml",{cliente_id:id,confirmar:"SINCRONIZAR"});
  if(action==="feed"&&request.method==="GET"){const feed=(await file(env,`private/clientes/${id}/feed.json`)).data;return feed?json(feed):json({erro:"Feed não configurado"},404)}
  if(action==="feed"&&request.method==="PUT"){const value={cliente_id:id,...safeFeed(await body(request))}, old=await file(env,`private/clientes/${id}/feed.json`);await save(env,`private/clientes/${id}/feed.json`,value,old.sha);return json({salvo:true})}
  if(action==="feed"&&sub==="testar"&&request.method==="POST"){const configured=(await file(env,`private/clientes/${id}/feed.json`)).data;if(!configured)return json({erro:"Feed não configurado"},404);safeFeed(configured);try{const response=await fetch(configured.feed_url,{headers:{accept:"application/xml,text/xml"},redirect:"error"});const text=await response.text();const xml=response.ok&&/^\s*<\?xml|^\s*<[A-Za-z_]/.test(text);return json({url_acessivel:response.ok,https_valido:true,xml_valido:xml,estrutura_reconhecida:xml,quantidade_imoveis:null,campos_detectados:[],campos_desconhecidos:[],problemas:xml?[]:["Resposta não reconhecida como XML"],resultado:xml?"aprovado":"reprovado"})}catch{return json({url_acessivel:false,https_valido:true,xml_valido:false,estrutura_reconhecida:false,quantidade_imoveis:null,campos_detectados:[],campos_desconhecidos:[],problemas:["Não foi possível acessar o feed"],resultado:"reprovado"},422)}}
 }
 return json({erro:"Rota inexistente"},404)
 }catch(error){if(error instanceof RangeError)return json({erro:"Conteúdo excede o limite"},413);if(error instanceof SyntaxError)return json({erro:"JSON inválido"},400);if(error instanceof TypeError)return json({erro:error.message},400);return json({erro:"Falha interna"},500)}}

export const testables={authenticate,cookie,encodedPasswordHash,handle,passwordHash,session,verifyPassword};
export default{async fetch(request,env){const response=await handle(request,env),headers=new Headers(response.headers);headers.set("access-control-allow-origin",env.ADMIN_ORIGIN);headers.set("access-control-allow-credentials","true");headers.set("vary","Origin");return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}};
