const JSON_HEADERS = { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", "x-content-type-options": "nosniff" };
const json = (value, status = 200, headers = {}) => new Response(JSON.stringify(value), { status, headers: { ...JSON_HEADERS, ...headers } });
const encode = bytes => btoa(String.fromCharCode(...bytes)).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", "");
const bytes = value => new TextEncoder().encode(value);
const attempts = new Map();
function limited(key) { const now=Date.now(), recent=(attempts.get(key)||[]).filter(value=>now-value<900000); recent.push(now); attempts.set(key,recent); return recent.length>10; }
async function jsonBody(request) { const raw=await request.text(); if(bytes(raw).length>16384)throw new RangeError("payload"); return JSON.parse(raw); }
const constant = (a, b) => { if (a.length !== b.length) return false; let result = 0; for (let i=0;i<a.length;i++) result |= a.charCodeAt(i)^b.charCodeAt(i); return result===0; };
async function mac(value, secret) { const key=await crypto.subtle.importKey("raw",bytes(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]); return encode(new Uint8Array(await crypto.subtle.sign("HMAC",key,bytes(value)))); }
async function session(user, role, secret, ttl=3600) { const payload=encode(bytes(JSON.stringify({sub:user,role,exp:Math.floor(Date.now()/1000)+ttl}))); return `${payload}.${await mac(payload,secret)}`; }
async function authenticate(request, env) { const token=(request.headers.get("cookie")||"").match(/(?:^|; )session=([^;]+)/)?.[1]; if(!token)return null; const [payload,signature]=token.split("."); if(!constant(signature||"",await mac(payload||"",env.SESSION_SECRET)))return null; try { const data=JSON.parse(atob(payload.replaceAll("-","+").replaceAll("_","/").padEnd(Math.ceil(payload.length/4)*4,"="))); return data.exp>Date.now()/1000&&["superadmin","cliente"].includes(data.role)&&typeof data.sub==="string"?data:null; } catch{return null;} }
async function passwordHash(password, salt, iterations=310000) { const material=await crypto.subtle.importKey("raw",bytes(password),"PBKDF2",false,["deriveBits"]); return encode(new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:bytes(salt),iterations},material,256))); }
async function verifyPassword(password, stored) { if(typeof stored!=="string")return false; const [scheme,iterations,salt,hash]=stored.split("$"); if(scheme!=="pbkdf2-sha256"||iterations!=="310000"||!/^[A-Za-z0-9_-]{16,64}$/.test(salt||"")||!/^[A-Za-z0-9_-]{40,64}$/.test(hash||""))return false; return constant(await passwordHash(password,salt,310000),hash); }
const validId=id=>/^[a-z0-9][a-z0-9-]{2,39}$/.test(id);
async function github(env, path, options={}) { const response=await fetch(`https://api.github.com/repos/${env.GITHUB_OWNER}/${env.GITHUB_REPO}${path}`,{...options,headers:{accept:"application/vnd.github+json",authorization:`Bearer ${env.GITHUB_ADMIN_TOKEN}`,"x-github-api-version":"2022-11-28","user-agent":"portal-londrinense-admin",...(options.headers||{})}}); if(!response.ok)throw new Error(`GitHub ${response.status}`); return response.status===204?null:response.json(); }
async function file(env,path) { try { const data=await github(env,`/contents/${path}?ref=${env.GITHUB_BRANCH}`); return {data:JSON.parse(decodeURIComponent(escape(atob(data.content.replace(/\s/g,""))))),sha:data.sha}; } catch{return {data:null,sha:null};} }
async function save(env,path,value,sha) { const body={message:`admin: atualiza ${path.split("/").at(-1)}`,branch:env.GITHUB_BRANCH,content:btoa(unescape(encodeURIComponent(JSON.stringify(value,null,2)+"\n")))}; if(sha)body.sha=sha; return github(env,`/contents/${path}`,{method:"PUT",body:JSON.stringify(body)}); }
function cookie(token) { return `session=${token}; Path=/; Max-Age=3600; HttpOnly; Secure; SameSite=Strict`; }
export const testables = {authenticate, cookie, session, verifyPassword};
async function handle(request,env) { try {
  const url=new URL(request.url); if(url.protocol!=="https:")return json({erro:"HTTPS obrigatório"},400);
  const origin=request.headers.get("origin");
  if(origin!==env.ADMIN_ORIGIN)return json({erro:"Origem não autorizada"},403);
  if(request.method==="OPTIONS")return new Response(null,{status:204,headers:{allow:"GET, POST, PUT, OPTIONS","access-control-allow-origin":env.ADMIN_ORIGIN,"access-control-allow-credentials":"true","access-control-allow-headers":"content-type","vary":"Origin"}});
  if(["POST","PUT"].includes(request.method)&&(request.headers.get("content-type")||"").split(";")[0]!=="application/json")return json({erro:"Conteúdo inválido"},415);
  if(Number(request.headers.get("content-length")||0)>16384)return json({erro:"Conteúdo excede o limite"},413);
  if(url.pathname==="/api/login"&&request.method==="POST") { const key=request.headers.get("cf-connecting-ip")||"desconhecido";if(limited(key))return json({erro:"Muitas tentativas"},429); const body=await jsonBody(request); if(typeof body.usuario!=="string"||typeof body.senha!=="string"||body.senha.length>256)return json({erro:"Entrada inválida"},400); if(body.usuario===env.SUPERADMIN_USER&&await verifyPassword(body.senha,env.SUPERADMIN_PASSWORD_HASH))return json({papel:"superadmin"},200,{"set-cookie":cookie(await session(body.usuario,"superadmin",env.SESSION_SECRET)),"access-control-allow-origin":env.ADMIN_ORIGIN,"access-control-allow-credentials":"true"}); const id=body.usuario; if(validId(id)){const account=(await file(env,`private/clientes/${id}/acesso.json`)).data;if(account?.ativo&&await verifyPassword(body.senha,account.senha_hash))return json({papel:"cliente"},200,{"set-cookie":cookie(await session(id,"cliente",env.SESSION_SECRET)),"access-control-allow-origin":env.ADMIN_ORIGIN,"access-control-allow-credentials":"true"});} return json({erro:"Credenciais inválidas"},401); }
  if(url.pathname==="/api/primeiro-acesso"&&request.method==="POST") { const body=await jsonBody(request); if(!validId(body.cliente_id||"")||typeof body.token!=="string"||typeof body.nova_senha!=="string"||body.nova_senha.length<12||body.nova_senha.length>256)return json({erro:"Entrada inválida"},400);const existing=await file(env,`private/clientes/${body.cliente_id}/acesso.json`),account=existing.data;if(!account?.primeiro_acesso||new Date(account.redefinicao_expira)<=new Date()||!constant(account.redefinicao_hash||"",await mac(body.token,env.SESSION_SECRET)))return json({erro:"Desafio inválido ou expirado"},401);const salt=encode(crypto.getRandomValues(new Uint8Array(16)));await save(env,`private/clientes/${body.cliente_id}/acesso.json`,{cliente_id:body.cliente_id,ativo:true,primeiro_acesso:false,senha_hash:`pbkdf2-sha256$310000$${salt}$${await passwordHash(body.nova_senha,salt)}`},existing.sha);return json({acesso_configurado:true}); }
  if(url.pathname==="/api/logout"&&request.method==="POST")return json({ok:true},200,{"set-cookie":"session=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict"});
  const auth=await authenticate(request,env); if(!auth)return json({erro:"Não autenticado"},401);
  if(url.pathname==="/api/clientes"&&request.method==="PUT") { if(auth.role!=="superadmin")return json({erro:"Proibido"},403);const body=await jsonBody(request),id=body.id;if(!validId(id)||typeof body.nome!=="string"||body.nome.length<1||body.nome.length>160||!["imobiliaria","corretor"].includes(body.tipo))return json({erro:"Cliente inválido"},400);const allowed=["id","nome","tipo","creci","cidade","uf","descricao","logo","razao_social","documento","responsavel","email","telefone","observacoes","ativo"];if(Object.keys(body).some(key=>!allowed.includes(key)))return json({erro:"Campo inválido"},400);const existing=await file(env,`private/clientes/${id}/cliente.json`);await save(env,`private/clientes/${id}/cliente.json`,{...body,id,ativo:body.ativo!==false},existing.sha);return json({salvo:true});}
  if(url.pathname==="/api/sincronizar"&&request.method==="POST") { if(auth.role!=="superadmin")return json({erro:"Proibido"},403); if(env.ENABLE_REAL_SYNC!=="true")return json({modo:"dry-run",mensagem:"Sincronização real desabilitada"}); await github(env,"/actions/workflows/sincronizar.yml/dispatches",{method:"POST",body:JSON.stringify({ref:env.GITHUB_BRANCH,inputs:{confirmar:"SINCRONIZAR"}})}); return json({iniciado:true},202); }
  const match=url.pathname.match(/^\/api\/clientes\/([a-z0-9-]+)(?:\/(feed|acesso|sincronizar))?$/); if(match){const id=match[1],action=match[2];if(!validId(id)||(auth.role!=="superadmin"&&auth.sub!==id))return json({erro:"Proibido"},403);
    if(!action&&request.method==="GET"){const client=(await file(env,`private/clientes/${id}/cliente.json`)).data;if(!client)return json({erro:"Cliente inexistente"},404);return json(client);}
    if(action==="sincronizar"&&request.method==="POST"){if(env.ENABLE_REAL_SYNC!=="true")return json({modo:"dry-run"});await github(env,"/actions/workflows/sincronizar-cliente.yml/dispatches",{method:"POST",body:JSON.stringify({ref:env.GITHUB_BRANCH,inputs:{cliente_id:id,confirmar:"SINCRONIZAR"}})});return json({iniciado:true},202);}
    if(action==="acesso"&&request.method==="POST"){if(auth.role!=="superadmin")return json({erro:"Proibido"},403);const token=encode(crypto.getRandomValues(new Uint8Array(24))),salt=encode(crypto.getRandomValues(new Uint8Array(16))),existing=await file(env,`private/clientes/${id}/acesso.json`);await save(env,`private/clientes/${id}/acesso.json`,{cliente_id:id,ativo:true,primeiro_acesso:true,redefinicao_hash:await mac(token,env.SESSION_SECRET),redefinicao_expira:new Date(Date.now()+3600000).toISOString(),senha_hash:`pbkdf2-sha256$310000$${salt}$${await passwordHash(token,salt)}`},existing.sha);return json({token_primeiro_acesso:token,expira_em_segundos:3600});}
    if(action==="feed"&&request.method==="PUT"){const body=await jsonBody(request);let feed;try{feed=new URL(body.feed_url);}catch{return json({erro:"Feed inválido"},400);}if(typeof body.feed_url!=="string"||body.feed_url.length>2048||feed.protocol!=="https:"||feed.username||feed.password||feed.hash||!feed.hostname)return json({erro:"Feed inválido"},400);const existing=await file(env,`private/clientes/${id}/feed.json`);await save(env,`private/clientes/${id}/feed.json`,{cliente_id:id,feed_url:body.feed_url,origem:String(body.origem||"generico").slice(0,50),formato:"xml",ativo:body.ativo!==false},existing.sha);return json({salvo:true});}
  }
  return json({erro:"Rota inexistente"},404);
} catch (error) { return error instanceof RangeError&&error.message==="payload"?json({erro:"Conteúdo excede o limite"},413):json({erro:"Falha interna"},500); } }

export default { async fetch(request, env) {
  const response = await handle(request, env);
  const headers = new Headers(response.headers);
  headers.set("access-control-allow-origin", env.ADMIN_ORIGIN);
  headers.set("access-control-allow-credentials", "true");
  headers.set("vary", "Origin");
  return new Response(response.body, {status: response.status, statusText: response.statusText, headers});
} };
